version: "3.8"

services:
  # Serviço para o Backend (bytebank-api)
  api:
    build:
      # O contexto aponta para a pasta do seu backend
      context: ../bytebank-api
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    command: bash -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    volumes:
      # Monta o código-fonte para hot-reload
      - ../bytebank-api/src:/app/src
      - ../bytebank-api/prisma:/app/prisma
    env_file:
      - ../bytebank-api/.env # Garante que o DATABASE_URL seja carregado
    restart: always
    depends_on:
      - db

  # Serviço para o Frontend Host (angular-host)
  angular-host:
    build:
      context: ./frontend/angular-host
      dockerfile: Dockerfile
    ports:
      - "4200:4200" # Porta padrão do Angular
    restart: always
    volumes:
      - ./frontend/angular-host:/app # Monta o código-fonte para hot-reload
      - /app/node_modules # Isola o node_modules para não ser sobrescrito pelo volume do host
    depends_on:
      - api

  # Serviço para o Frontend Remoto (angular-remote)
  angular-remote:
    build:
      context: ./frontend/angular-remote
      dockerfile: Dockerfile
    ports:
      - "4201:4201" # Porta diferente para o micro-frontend
    restart: always
    volumes:
      - ./frontend/angular-remote:/app # Monta o código-fonte para hot-reload
      - /app/node_modules # Isola o node_modules para não ser sobrescrito pelo volume do host
    depends_on:
      - api

  # Serviço para o Banco de Dados (PostgreSQL)
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bytebank # Usuário do banco
      POSTGRES_PASSWORD: bytebank@2025 # Senha do banco
      POSTGRES_DB: bytebank_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
