version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres/${DB}?schema=public&timezone=America/Sao_Paulo
    restart: always
    depends_on:
      - postgres
    networks:
      - bytebank-net

  angular-host:
    build:
      context: ./frontend/angular-host
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    command: sh -c "npm run start"
    restart: always
    volumes:
      - ./frontend/angular-host:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - bytebank-net

  angular-remote:
    build:
      context: ./frontend/angular-remote
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    command: sh -c "npm run start"
    restart: always
    volumes:
      - ./frontend/angular-remote:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - bytebank-net

  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bytebank-net

volumes:
  pgdata:
    driver: local

networks:
  bytebank-net:
    driver: bridge
